export function menu() { 

    const leftDiv = document.createElement("div");
    const cards = document.createElement("div"); 
    const card1 = document.createElement("div"); 
    const card2 = document.createElement("div"); 
    const card3 = document.createElement("div"); 
    const card4 = document.createElement("div");
    const card5 = document.createElement("div");
    const card6 = document.createElement("div");
    const title1 = document.createElement("h1");
    const title2 = document.createElement("h1");
    const title3 = document.createElement("h1");
    const title4 = document.createElement("h1");
    const title5 = document.createElement("h1");
    const title6 = document.createElement("h1");
    const text1 = document.createElement("p");
    const text2 = document.createElement("p");
    const text3 = document.createElement("p");
    const text4 = document.createElement("p");
    const text5 = document.createElement("p");
    const text6 = document.createElement("p");
    leftDiv.classList.add('homeLeft'); 
    cards.classList.add('cards'); 
    card1.classList.add("contentDiv");
    card2.classList.add("contentDiv");
    card3.classList.add("contentDiv");
    card4.classList.add("contentDiv");
    card5.classList.add("contentDiv");
    card6.classList.add("contentDiv");
    title1.classList.add("cardTitle");
    title2.classList.add("cardTitle");
    title3.classList.add("cardTitle");
    title4.classList.add("cardTitle");
    title5.classList.add("cardTitle");
    title6.classList.add("cardTitle");
    title1.innerHTML = "Seco de Pollo";
    title2.innerHTML = "Seco de Chivo";
    title3.innerHTML = "Guatita";
    title4.innerHTML = "Menestra de Pollo";
    title5.innerHTML = "Tigrillo";
    title6.innerHTML = "Caldo de Bola";
    text1.innerHTML = "Esto es un texto de prueba para comprobar el contenido";
    text2.innerHTML = "Esto es un texto de prueba para comprobar el contenido";
    text3.innerHTML = "Esto es un texto de prueba para comprobar el contenido";
    text4.innerHTML = "Esto es un texto de prueba para comprobar el contenido";
    text5.innerHTML = "Esto es un texto de prueba para comprobar el contenido";
    text6.innerHTML = "Esto es un texto de prueba para comprobar el contenido";
    card1.appendChild(title1);
    card2.appendChild(title2);
    card3.appendChild(title3);
    card4.appendChild(title4);
    card5.appendChild(title5);
    card6.appendChild(title6);
    card1.appendChild(text1);
    card2.appendChild(text2);
    card3.appendChild(text3);
    card4.appendChild(text4);
    card5.appendChild(text5);
    card6.appendChild(text6);
    cards.appendChild(card1);
    cards.appendChild(card2);
    cards.appendChild(card3);
    cards.appendChild(card4);
    cards.appendChild(card5);
    cards.appendChild(card6);
    leftDiv.appendChild(cards);
    return leftDiv;

}